name: todo
description: Simple todo app.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  english_words: ^3.1.5
  flutter:
    sdk: flutter
  sqflite: ^1.2.0
  path:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true